
package com.empleado.cr.view;

import com.usuario.cr.bo.UsuarioBO;
import com.usuario.cr.entity.Usuario;
import javax.swing.JOptionPane;


public class FrmUsuario extends javax.swing.JFrame {

  
    private UsuarioBO ubo = new UsuarioBO();
    public FrmUsuario() {
        initComponents();
        listarUsuarios();
        idMax();
    }
    
    public void listarUsuarios(){
        ubo.listarUsuario(tbUsuario);
    }
    public void idMax(){
        txtIdUsuario.setText(ubo.getMaxID()+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtEmailUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCedulaUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        txtApellidoPUsuario = new javax.swing.JTextField();
        txtApellidoMUsuario = new javax.swing.JTextField();
        txtEdadUsuario = new javax.swing.JTextField();
        txtPesoUsuario = new javax.swing.JTextField();
        txtTallaUsuario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUsuario = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtIdUsuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        setForeground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EMAIL:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        txtEmailUsuario.setBackground(new java.awt.Color(0, 0, 0));
        txtEmailUsuario.setFont(new java.awt.Font("Roboto Light", 2, 14)); // NOI18N
        txtEmailUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtEmailUsuario.setText("Ingrese su email...");
        txtEmailUsuario.setBorder(null);
        txtEmailUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmailUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 300, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("FORMULARIO USUARIO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        txtCedulaUsuario.setBackground(new java.awt.Color(0, 0, 0));
        txtCedulaUsuario.setFont(new java.awt.Font("Roboto Light", 2, 14)); // NOI18N
        txtCedulaUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtCedulaUsuario.setText("Ingrese la cedula...");
        txtCedulaUsuario.setBorder(null);
        txtCedulaUsuario.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCedulaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtCedulaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 300, 20));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NOMBRES:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PESO:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("APELLIDO P:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("APELLIDO M:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("EDAD:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("TALLA:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        txtNombreUsuario.setBackground(new java.awt.Color(0, 0, 0));
        txtNombreUsuario.setFont(new java.awt.Font("Roboto Light", 2, 14)); // NOI18N
        txtNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreUsuario.setText("Ingrese el nombre...");
        txtNombreUsuario.setBorder(null);
        txtNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 300, -1));

        txtApellidoPUsuario.setBackground(new java.awt.Color(0, 0, 0));
        txtApellidoPUsuario.setFont(new java.awt.Font("Roboto Light", 2, 14)); // NOI18N
        txtApellidoPUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtApellidoPUsuario.setText("Ingrese el apellido paterno...");
        txtApellidoPUsuario.setBorder(null);
        txtApellidoPUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtApellidoPUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 300, 20));

        txtApellidoMUsuario.setBackground(new java.awt.Color(0, 0, 0));
        txtApellidoMUsuario.setFont(new java.awt.Font("Roboto Light", 2, 14)); // NOI18N
        txtApellidoMUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtApellidoMUsuario.setText("Ingrese el apellido materno...");
        txtApellidoMUsuario.setBorder(null);
        txtApellidoMUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtApellidoMUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 300, -1));

        txtEdadUsuario.setBackground(new java.awt.Color(0, 0, 0));
        txtEdadUsuario.setFont(new java.awt.Font("Roboto Light", 2, 14)); // NOI18N
        txtEdadUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtEdadUsuario.setText("Ingrese el edad...");
        txtEdadUsuario.setToolTipText("");
        txtEdadUsuario.setBorder(null);
        txtEdadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtEdadUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 300, -1));

        txtPesoUsuario.setBackground(new java.awt.Color(0, 0, 0));
        txtPesoUsuario.setFont(new java.awt.Font("Roboto Light", 2, 14)); // NOI18N
        txtPesoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtPesoUsuario.setText("Ingrese el peso...");
        txtPesoUsuario.setBorder(null);
        txtPesoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtPesoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 300, -1));

        txtTallaUsuario.setBackground(new java.awt.Color(0, 0, 0));
        txtTallaUsuario.setFont(new java.awt.Font("Roboto Light", 2, 14)); // NOI18N
        txtTallaUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtTallaUsuario.setText("Ingrese la talla (cm)...");
        txtTallaUsuario.setBorder(null);
        txtTallaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTallaUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtTallaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 300, -1));

        tbUsuario.setBackground(new java.awt.Color(153, 153, 153));
        tbUsuario.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        tbUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbUsuario.setGridColor(new java.awt.Color(153, 153, 153));
        tbUsuario.setSelectionBackground(new java.awt.Color(255, 0, 0));
        tbUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbUsuario);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 850, 320));

        btnSalir.setBackground(new java.awt.Color(255, 0, 0));
        btnSalir.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.setBorder(null);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 420, 140, 40));

        btnAgregar.setBackground(new java.awt.Color(255, 0, 0));
        btnAgregar.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(null);
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 140, 40));

        btnEditar.setBackground(new java.awt.Color(255, 0, 0));
        btnEditar.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.setBorder(null);
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 140, 40));

        btnBorrar.setBackground(new java.awt.Color(255, 0, 0));
        btnBorrar.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar.setText("Borrar");
        btnBorrar.setBorder(null);
        btnBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 140, 40));

        btnLimpiar.setBackground(new java.awt.Color(255, 0, 0));
        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(null);
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 140, 40));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 300, 10));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 300, 20));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 300, 10));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 300, 10));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 150, 10));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator8.setToolTipText("");
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 150, -1));

        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 150, 10));

        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 310, -1));

        jLabel10.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CEDULA:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel11.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ID:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txtIdUsuario.setBorder(null);
        jPanel1.add(txtIdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 30, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailUsuarioActionPerformed

    private void txtCedulaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaUsuarioActionPerformed

    private void txtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioActionPerformed

    private void txtApellidoPUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoPUsuarioActionPerformed

    private void txtApellidoMUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMUsuarioActionPerformed

    private void txtEdadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadUsuarioActionPerformed

    private void txtPesoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoUsuarioActionPerformed

    private void txtTallaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTallaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTallaUsuarioActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if(txtCedulaUsuario.getText().isEmpty() || txtNombreUsuario.getText().isEmpty() || txtApellidoPUsuario.getText().isEmpty() || txtApellidoMUsuario.getText().isEmpty() || txtEdadUsuario.getText().isEmpty() || txtPesoUsuario.getText().isEmpty() || txtTallaUsuario.getText().isEmpty() || txtEmailUsuario.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Por favor no deje campos vacios");
            
        }else{
            Usuario usu= new Usuario();
            usu.setIDUSUARIO(Integer.parseInt(txtIdUsuario.getText()));
            usu.setCEDULA(Integer.parseInt(txtCedulaUsuario.getText()));
            usu.setNOMBRE(txtNombreUsuario.getText());
            usu.setAPELLIDOP(txtApellidoPUsuario.getText());
            usu.setAPELLIDOM(txtApellidoMUsuario.getText());
            usu.setEDAD(Integer.parseInt(txtEdadUsuario.getText()));
            usu.setPESO(Integer.parseInt(txtPesoUsuario.getText()));
            usu.setTALLA(Integer.parseInt(txtTallaUsuario.getText()));
            usu.setEMAIL(txtEmailUsuario.getText());
            String mensaje=ubo.agregarUsuario(usu);
            JOptionPane.showMessageDialog(null, mensaje);
            limpiar();
            listarUsuarios();
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if(txtCedulaUsuario.getText().isEmpty() || txtNombreUsuario.getText().isEmpty() || txtApellidoPUsuario.getText().isEmpty() || txtApellidoMUsuario.getText().isEmpty() || txtEdadUsuario.getText().isEmpty() || txtPesoUsuario.getText().isEmpty() || txtTallaUsuario.getText().isEmpty() || txtEmailUsuario.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Por favor no deje campos vacios");
            
        }else{
            Usuario usu= new Usuario();
            
            usu.setIDUSUARIO(Integer.parseInt(txtIdUsuario.getText()));
            usu.setCEDULA(Integer.parseInt(txtCedulaUsuario.getText()));
            usu.setNOMBRE(txtNombreUsuario.getText());
            usu.setAPELLIDOP(txtApellidoPUsuario.getText());
            usu.setAPELLIDOM(txtApellidoMUsuario.getText());
            usu.setEDAD(Integer.parseInt(txtEdadUsuario.getText()));
            usu.setPESO(Integer.parseInt(txtPesoUsuario.getText()));
            usu.setTALLA(Integer.parseInt(txtTallaUsuario.getText()));
            usu.setEMAIL(txtEmailUsuario.getText());
            String mensaje=ubo.editarUsuario(usu);
            JOptionPane.showMessageDialog(null, mensaje);
            limpiar();
            listarUsuarios();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
       if(txtCedulaUsuario.getText().isEmpty() || txtNombreUsuario.getText().isEmpty() || txtApellidoPUsuario.getText().isEmpty() || txtApellidoMUsuario.getText().isEmpty() || txtEdadUsuario.getText().isEmpty() || txtPesoUsuario.getText().isEmpty() || txtTallaUsuario.getText().isEmpty() || txtEmailUsuario.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Por favor no deje campos vacios");
            
        }else{
            String mensaje=ubo.borrarUsuario(Integer.parseInt(txtCedulaUsuario.getText()));
            JOptionPane.showMessageDialog(null, mensaje);
            limpiar();
            listarUsuarios();
        }

    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
       limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tbUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUsuarioMouseClicked
        int seleccion= tbUsuario.rowAtPoint(evt.getPoint());
        txtIdUsuario.setText(tbUsuario.getValueAt(seleccion, 0)+"");
        txtCedulaUsuario.setText(tbUsuario.getValueAt(seleccion, 1)+"");
        txtNombreUsuario.setText(tbUsuario.getValueAt(seleccion, 2)+"");
        txtApellidoPUsuario.setText(tbUsuario.getValueAt(seleccion, 3)+"");
        txtApellidoMUsuario.setText(tbUsuario.getValueAt(seleccion, 4)+"");
        txtEdadUsuario.setText(tbUsuario.getValueAt(seleccion, 5)+"");
        txtPesoUsuario.setText(tbUsuario.getValueAt(seleccion, 6)+"");
        txtTallaUsuario.setText(tbUsuario.getValueAt(seleccion, 7)+"");
        txtEmailUsuario.setText(tbUsuario.getValueAt(seleccion, 8)+"");
    }//GEN-LAST:event_tbUsuarioMouseClicked
    
    
    public void limpiar(){
       txtCedulaUsuario.setText("");
       txtNombreUsuario.setText("");
       txtApellidoPUsuario.setText("");
       txtApellidoMUsuario.setText("");
       txtEdadUsuario.setText("");
       txtPesoUsuario.setText("");
       txtTallaUsuario.setText("");
       txtEmailUsuario.setText("");
       idMax();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable tbUsuario;
    private javax.swing.JTextField txtApellidoMUsuario;
    private javax.swing.JTextField txtApellidoPUsuario;
    private javax.swing.JTextField txtCedulaUsuario;
    private javax.swing.JTextField txtEdadUsuario;
    private javax.swing.JTextField txtEmailUsuario;
    private javax.swing.JTextField txtIdUsuario;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtPesoUsuario;
    private javax.swing.JTextField txtTallaUsuario;
    // End of variables declaration//GEN-END:variables
}
